export const LANDING_LOCATORS = {
  nav: 'nav',
  navBrand: '.nav-brand',
  heroSection: '#hero',
  heroHeading: '#hero h1',
  heroRole: '.hero-role',
  aboutSection: '#about',
  skillsSection: '#skills',
  skillCategories: '.skill-category',
  projectsSection: '#projects',
  projectCards: '.project-card',
  experienceSection: '#experience',
  contactSection: '#contact',
  contactForm: '.contact-form',
  nameInput: '#name',
  emailInput: '#email',
  messageInput: '#message',
  submitButton: '#submit-btn',
  footer: 'footer',
};
